// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  angular.module('projectApp').config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: 'app/main/main.html',
      controller: 'MainCtrl'
    }).when('/energiebesparen', {
      templateUrl: 'app/main/energieBesparen/energiebesparen.html'
      controller: 'MainCtrl'
    });
  });

}).call(this);

//# sourceMappingURL=main.js.map

